# Generated by Django 5.2 on 2025-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discountcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='apply_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
