# Generated by Django 5.2 on 2025-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_refundrequest_refund_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de entradas'),
        ),
    ]
