# Generated by Django 5.2 on 2025-05-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ticket_quantity'),
        ('app', '0016_satisfactionsurvey'),
    ]

    operations = [
    ]
