# Generated by Django 5.2 on 2025-05-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='apply_to_all',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='app.event'),
        ),
    ]
