# Generated by Django 5.2 on 2025-05-28 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
