# Generated by Django 5.2 on 2025-05-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_discountcode_apply_to_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.discountcode', verbose_name='Código de Descuento'),
        ),
    ]
